# Generated by Django 2.0.2 on 2018-02-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=10000)),
                ('address', models.TextField()),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
    ]
